### ISSUE TITLE
KeyNotFoundException on first use

### ISSUE THREAD

**Issue by idbrii** [blueberryzzz/ReferenceFinder#5]
The first time I use ReferenceFinder in a project, I get "KeyNotFoundException: The given key was not present in the dictionary."

If you comment out the try/catch, you can see that it's from ReferenceFinder\ReferenceFinderData.cs:60

                assetDict[assetGuid].references.Add(asset.Key);

Probably just needs to use TryGetValue instead of [].

Seen on Unity 2019.4.16.

**Comment by justinlm** [comment]
There is a Pull request "fix KeyNotFoundException bug and repeated references bug
#6 opened on 28 Feb 2021 by JWhiteCat" can fix this bug.
