### ISSUE TITLE
重复显示

### ISSUE THREAD

**Issue by bluedoom** [blueberryzzz/ReferenceFinder#7]
![image](https://user-images.githubusercontent.com/29087010/121491127-428cb980-ca08-11eb-9598-c924a67f07f2.png)
查找引用模式下，会有一些资源重复出现

**Comment by dengxuhui** [comment]
![image](https://user-images.githubusercontent.com/31962035/148519073-f2adaf7e-5697-4938-9739-7a188c23e31b.png)
修改ReferenceFinderData.UpdateReferenceInfo即可

**Comment by blueberryzzz** [comment]
done
